name = "Skyblocker Modpack"
author = "TacoMonkey, Wohlhabend"
version = "2.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6220ef5b08af69960779be0c939cf13cefccd983c8a37e65241e21c67c76d2ad"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
