name = "Skyblocker Modpack"
author = "Wohlhabend, TacoMonkey"
version = "3.0.0-alpha.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1df0698cffbec85dc85bad523ca1d86dfab92db3986b8d4fe58922e2ea01c4de"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
