name = "Skyblocker Modpack"
author = "TacoMonkey, Wohlhabend"
version = "2.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d94908e2a1094ad4fa1a30ba80441499ebe1fd386c8d81cbecc0b724d56254fa"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
