name = "Skyblocker Modpack"
author = "TacoMonkey, Wohlhabend"
version = "2.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1bffdcd1b442988c1917c155b4faa99a3910f1ae48e5f050e16201a181dadc8c"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
