name = "Skyblocker Modpack"
author = "TacoMonkey, Wohlhabend"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe51da3843626b06e2ef3581f3aa19a0702300b7afbf769b3687b32878756078"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
