name = "Skyblocker Modpack"
author = "TacoMonkey, Wohlhabend"
version = "1.3.6"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "319e2f8e775da337683bbd79308843a4bcd93449642d301f731aaae93c762a88"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.1"]
