name = "Skyblocker Modpack"
author = "Wohlhabend, TacoMonkey"
version = "3.0.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1599b9f53ec1f777b054690fe7c0b32afc9a31a473b77a97ac4d7501a88a7770"

[versions]
fabric = "0.15.0"
minecraft = "1.20.2"
