name = "Skyblocker Modpack"
author = "Wohlhabend, TacoMonkey"
version = "3.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d277ab53003819d5fd772564d066e5a0cd7bb618b4b22f0973b77c0d6c6702f"

[versions]
fabric = "0.15.6"
minecraft = "1.20.4"
