name = "Skyblocker Modpack"
author = "TacoMonkey, Wohlhabend"
version = "1.3.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b6d4c6c00fdafc6af5334345b1f5ca24f25d4d765ce6be917397f6dd95bcc2a4"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.1"]
