name = "Skyblocker Modpack"
author = "Wohlhabend"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c94755febb5b8a99c378ab0671057679d2a0e11d030d600d18cd0e8ef07155fe"

[versions]
fabric = "0.12.3"
minecraft = "1.17.1"
