name = "Skyblocker Modpack"
author = "Wohlhabend, TacoMonkey"
version = "3.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bfb4171d88f3369332cbddaa0e5064cd9b4d50bd8bd544c08008966ce838f308"

[versions]
fabric = "0.15.6"
minecraft = "1.20.4"
