name = "Skyblocker Modpack"
author = "TacoMonkey, Wohlhabend"
version = "1.3.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed94dd93b9a4877de8a0b4e7ed493c4982de18d0c629f24072221446269cc048"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.1"]
