name = "Skyblocker Modpack"
author = "TacoMonkey, Wohlhabend"
version = "1.5.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "67767db56274fa6e8a70178ab1c5ba48e77991488d220a8554d0209d5cab0fab"

[versions]
fabric = "0.14.3"
minecraft = "1.18.2"
