name = "Skyblocker Modpack"
author = "Wohlhabend, TacoMonkey"
version = "3.0.23"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16818bba91ae940482a345c68e4eeab926e643a62d33acbce3d5c5cd09b68089"

[versions]
fabric = "0.15.0"
minecraft = "1.20.2"
