name = "Skyblocker Modpack"
author = "TacoMonkey, Wohlhabend"
version = "1.3.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "51a2bcc106ed25e137cc2d5b5c8c6939ac954fd9d8b14f2e222826666fe6bb7a"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.1"]
