name = "Skyblocker Modpack"
author = "Wohlhabend, TacoMonkey"
version = "3.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1cf004fb8378907d9fceb95b60ca9dc26394d83045255b38621b0884e9fbf6b9"

[versions]
fabric = "0.14.23"
minecraft = "1.20.2"
