name = "Skyblocker Modpack"
author = "TacoMonkey, Wohlhabend"
version = "1.3.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a78da115128c813293437e2459314cbd5f2635a717c9037f2b87d328da875be"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
