name = "Skyblocker Modpack"
author = "Wohlhabend, TacoMonkey"
version = "3.0.0-alpha.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4cad71030aa7559125266a69938b11a986ea4ed238e79e0d64037909b7aa1edc"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
