name = "Skyblocker Modpack"
author = "Wohlhabend, TacoMonkey"
version = "3.0.13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b89522090e08044976f6a7d3b13dc0c9e293010e3142c71f3bec7e9e452cc7b6"

[versions]
fabric = "0.15.0"
minecraft = "1.20.2"
