name = "Skyblocker Modpack"
author = "Wohlhabend, TacoMonkey"
version = "3.0.15"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09dae7c7a08377bc3a9a4b6057bbd53ab67e48303d018e53878e9ff3bb4ee12e"

[versions]
fabric = "0.15.0"
minecraft = "1.20.2"
