name = "Skyblocker Modpack"
author = "Wohlhabend, TacoMonkey"
version = "3.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "943a36786391776c35bb98977bc21d3d003b84beffa4149f66d36360258cdd04"

[versions]
fabric = "0.15.0"
minecraft = "1.20.2"
