name = "Skyblocker Modpack"
author = "TacoMonkey, Wohlhabend"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66fb157c728b5e4b2cc92c0a7f7893ac7a722792cd5b18bf080f5ee19532accb"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
