name = "Skyblocker Modpack"
author = "Wohlhabend, TacoMonkey"
version = "3.0.21"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d74dcf144adaa91e1618963a958a8ccf3821dcf8b3f6a040f4ddaade48e8360a"

[versions]
fabric = "0.15.0"
minecraft = "1.20.2"
