name = "Skyblocker Modpack"
author = "TacoMonkey, Wohlhabend"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ebca39946d65be31d32c74ebecedf9627c1c4bbd78819c6045e402a18cdec6d7"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
