name = "Skyblocker Modpack"
author = "TacoMonkey, Wohlhabend"
version = "1.3.7"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38bbd4517ddb58b4888b322326cc581b5ce87f301c5f2bc67b8397281d99a687"

[versions]
fabric = "0.14.3"
minecraft = "1.18.2"
