name = "Skyblocker Modpack"
author = "Wohlhabend, TacoMonkey"
version = "3.4.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66c4cf64d6a12155e2d48fa86698457a6366a6445ed09fd2b238f82d6eb04967"

[versions]
fabric = "0.15.11"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.21"]
