name = "Skyblocker Modpack"
author = "TacoMonkey, Wohlhabend"
version = "1.3.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6dd3c78ffded4bb7a7cf400c315d43a4119fef56809549e78cc667026e62316d"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.1"]
