name = "Skyblocker Modpack"
author = "Wohlhabend, TacoMonkey"
version = "3.0.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7fe7672ade549fad1bf00ab98e14a5d129e2b12c0468f8515375d3d733c861ed"

[versions]
fabric = "0.15.0"
minecraft = "1.20.2"
