name = "Skyblocker Modpack"
author = "TacoMonkey, Wohlhabend"
version = "1.4.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f6647be3c344111e7318161a0d50351c1fd0a9dcad15703635dd9c8da6adb42"

[versions]
fabric = "0.14.3"
minecraft = "1.18.2"
