name = "Skyblocker Modpack"
author = "TacoMonkey, Wohlhabend"
version = "1.4.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4efce65cd2fcc86bf82cc5c132d3198530d43955bcb7be9140b334ce0bc8aaa4"

[versions]
fabric = "0.14.3"
minecraft = "1.18.2"
