name = "Skyblocker Modpack"
author = "Wohlhabend, TacoMonkey"
version = "3.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d88d33058123c76cb69dc36e639d6028228a6cabd1825f158c7e94e662651612"

[versions]
fabric = "0.15.6"
minecraft = "1.20.4"
