name: Release Pack

on:
  push:
    branches:
    - master
  workflow_dispatch:
  
jobs:
  export_pack:
    name: Export Pack
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3
      
      - name: Setup Go environment
        uses: actions/setup-go@v4.0.0
        
      - name: Install Packwiz
        run: go install github.com/packwiz/packwiz@latest
      
      - name: Export modpack
        run: packwiz mr export

      - name: Set changelog environment variable
        run: echo "changelog=$(sed '/___/Q' CHANGELOG.md | grep -v '# ')" >> $GITHUB_ENV
    
      - uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: KmiWHzQ4
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          changelog: ${{ env.changelog }}
          
          github-token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          
          files-primary: Skyblocker Modpack-*.mrpack
          loaders: |
            fabric
